# Generated by Django 4.2.7 on 2023-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_query_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='response',
            field=models.TextField(default='output'),
            preserve_default=False,
        ),
    ]
